[workspace]
resolver = "2"
members = [
    "packages/blueflame", 
    "packages/blueflame-deps", 
    "packages/blueflame-proc-macros", 
    "packages/manual",
    "packages/parser", 
    "packages/runtime",
    "packages/runtime-tests",
    "packages/runtime-wasm",
]
