[package]
name = "blueflame-singleton"
version = "0.0.0"
edition = "2021"
description = "System for initializaing singletons in BlueFlame"

[dependencies.blueflame-utils]
path = "../blueflame-utils"

[dependencies]
deku = { version = "0.19.0", optional = true }
log = "0.4.27"
serde = { version = "1.0.217", features = ["derive"], optional = true }
static_assertions = "1.1.0"

[features]
deku = ["dep:deku", "blueflame-utils/deku"]
serde = ["dep:serde", "blueflame-utils/serde"]
